[package]
name = "rsclaw-watch"
version = "0.1.0"
publish = false
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
futures = "0.3"
bytes = "1"
reqwest = { version = "0.12", features = ["json", "stream", "multipart", "blocking", "rustls-tls-webpki-roots-no-provider", "socks"], default-features = false }
eventsource-stream = "0.2"
regex = "1"
uuid = { version = "1", features = ["v4"] }
jaq-core = "3"
jaq-json = { version = "2", features = ["sync"] }
jaq-std = "3"
rsclaw-config = { path = "../rsclaw-config" }
rsclaw-channel = { path = "../rsclaw-channel" }
rsclaw-util = { path = "../rsclaw-util" }
rsclaw-i18n = { path = "../rsclaw-i18n" }
rsclaw-platform = { path = "../rsclaw-platform" }

[dev-dependencies]
tempfile = "3"
