[package]
name = "rsclaw-provider"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tracing = "0.1"
base64 = "0.22"
url = "2"
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
toml = "1"
bytes = "1"
async-trait = "0.1"
eventsource-stream = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
reqwest = { version = "0.12", features = ["json", "stream", "multipart", "blocking", "rustls-tls-webpki-roots-no-provider", "socks"], default-features = false }
rsclaw-types = { path = "../rsclaw-types" }
rsclaw-config = { path = "../rsclaw-config" }
rsclaw-util = { path = "../rsclaw-util" }
rsclaw-i18n = { path = "../rsclaw-i18n" }

[dev-dependencies]
wiremock = "0.6"
