[package]
name = "rsclaw-a2a-types"
version = "0.1.0"
publish = false
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", features = ["full"] }
dashmap = "6"
uuid = { version = "1", features = ["v4"] }
anyhow = "1"
futures = "0.3"
reqwest = { version = "0.12", features = ["json", "stream", "multipart", "blocking", "rustls-tls-webpki-roots-no-provider", "socks"], default-features = false }
eventsource-stream = "0.2"
